packages:
  - apps/*
  - packages/*

catalog:
  '@arethetypeswrong/cli': 0.18.5
  '@types/node': 26.6.2
  publint: 0.3.24
  typescript: 7.0.2

autoDedupe: true
engineStrict: true
minimumReleaseAge: 1440
saveExact: true
